### ISSUE TITLE
Error when attempting to download The Glowing Man by Swans

### ISSUE THREAD

**Issue by gvbilello** [gvbilello/bc_ripper#1]
ERROR:
BC_Ripper
Beta version 0.1
---------------
Enter the url of the page you'd like to rip songs from:
https://swans.bandcamp.com/album/the-glowing-man
TralbumData found in script with index: 7
Downloading The Glowing Man, by Swans...
Downloading track 1, Cloud of Forgetting...
Downloading track 2, Cloud of Unknowing...
Downloading track 3, The World Looks Red / The World Looks Black...
bc_ripper.rb:92:in `initialize': No such file or directory @ rb_sysopen - Swans/The Glowing Man/Swans - The Glowing Man - 3 - The World Looks Red / The World Looks Black.mp3 (Errno::ENOENT)
	from bc_ripper.rb:92:in `copy_stream'
	from bc_ripper.rb:92:in `block in <main>'
	from bc_ripper.rb:89:in `each'
	from bc_ripper.rb:89:in `<main>'

I believe the issue is related to the fact that the third track 'The World Looks Red / The World Looks Black' contains a forward-slash, resulting in some kind of error in the code.  I'll look into fixing this.

**Comment by gvbilello** [comment]
Similar issue when attempting to download No One Deserves Happiness by The Body:

BC_Ripper
Beta version 0.1
---------------
Enter the url of the page you'd like to rip songs from:
https://thebody.bandcamp.com/
TralbumData found in script with index: 7
Downloading No One Deserves Happiness, by the body...
Downloading track 1, Wanderings...
Downloading track 2, Shelter Is Illusory...
Downloading track 3, For You...
Downloading track 4, Hallow / Hollow...
bc_ripper.rb:92:in `initialize': No such file or directory @ rb_sysopen - the body/No One Deserves Happiness/the body - No One Deserves Happiness - 4 - Hallow / Hollow.mp3 (Errno::ENOENT)
	from bc_ripper.rb:92:in `copy_stream'
	from bc_ripper.rb:92:in `block in <main>'
	from bc_ripper.rb:89:in `each'
	from bc_ripper.rb:89:in `<main>'

Definitely involves the forward-slash in the track title.  Will fix this by looking for a forward slash, or any other character that is not permitted in a file name, in the track title, and removing it when saving the file.

**Comment by gvbilello** [comment]
Error fixed in newest commit.
